// src/ai/anthropicProvider.js — real Claude provider (activates only when ANTHROPIC_API_KEY set).
// Returns the SAME shape as templateProvider so nothing else in the app changes.
// Falls back to the template provider on any error so the seller is never blocked.
const template = require("./templateProvider");

const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-5";
const FACTUAL = ["material", "dimensions", "weight", "warranty", "certifications", "packageContents", "countryOfOrigin"];

function systemPrompt(marketplace) {
  return `You are a product-listing writer for the ${marketplace} marketplace.
RULES:
- NEVER invent factual product information (material, dimensions, weight, warranty, certifications, package contents, country of origin, medical/safety claims). Use ONLY values the seller provided.
- If a factual value is missing, do not mention it. Do not use words like "premium", "original", "certified", "waterproof" unless supported by provided data.
- Output STRICT JSON only, no prose, matching the requested schema.`;
}
function userPrompt(input) {
  return `Seller-provided product data (JSON):
${JSON.stringify(input, null, 2)}

Return JSON with exactly these keys:
{"title":"...", "shortTitle":"...", "bullets":["..."], "description":"...", "keywords":["..."]}`;
}

async function generateListing(input, marketplace) {
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL, max_tokens: 1500,
        system: systemPrompt(marketplace),
        messages: [{ role: "user", content: userPrompt(input) }],
      }),
    });
    if (!res.ok) throw new Error("Anthropic HTTP " + res.status);
    const data = await res.json();
    const text = (data.content || []).map(c => c.text || "").join("");
    const json = JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1));
    const f = (value, conf = 0.9) => ({ value, sourceType: "ai_generated", confidence: conf, needsConfirmation: false });
    // reuse template's attribute logic (factual-safe) for the structured attributes
    const base = template.generateListing(input, marketplace);
    return {
      provider: "claude",
      note: "Generated by Claude from the seller's provided fields; missing facts are flagged, not invented.",
      fields: {
        title: f(json.title), shortTitle: f(json.shortTitle),
        bullets: f(json.bullets || []), description: f(json.description), keywords: f(json.keywords || []),
      },
      attributes: base.attributes,
    };
  } catch (e) {
    const fb = template.generateListing(input, marketplace);
    fb.note = "Claude unavailable (" + e.message + ") — used built-in generator as fallback.";
    return fb;
  }
}
module.exports = { generateListing };
