// src/ai/anthropicProvider.js — real Claude provider (activates only when ANTHROPIC_API_KEY set).
// Returns the SAME shape as templateProvider so nothing else in the app changes.
// Falls back to the template provider on any error so the seller is never blocked.
const template = require("./templateProvider");

const llm = require("./llm");
const FACTUAL = ["material", "dimensions", "weight", "warranty", "certifications", "packageContents", "countryOfOrigin"];

function systemPrompt(marketplace) {
  return `You are a product-listing writer for the ${marketplace} marketplace.
RULES:
- NEVER invent factual product information (material, dimensions, weight, warranty, certifications, package contents, country of origin, medical/safety claims). Use ONLY values the seller provided.
- If a factual value is missing, do not mention it. Do not use words like "premium", "original", "certified", "waterproof" unless supported by provided data.
- If a "brandProfile" is present, follow its tone, style and instructions, prefer its keywords, and NEVER use its prohibitedClaims.
- Output STRICT JSON only, no prose, matching the requested schema.`;
}
function userPrompt(input) {
  return `Seller-provided product data (JSON):
${JSON.stringify(input, null, 2)}

Return JSON with exactly these keys:
{"title":"...", "shortTitle":"...", "bullets":["..."], "description":"...", "keywords":["..."]}`;
}

async function generateListing(input, marketplace) {
  try {
    const out = await llm.chat({ system: systemPrompt(marketplace), user: userPrompt(input), maxTokens: 1500, biz: input.businessId || null });
    const json = llm.parseJSON(out.text);
    const f = (value, conf = 0.9) => ({ value, sourceType: "ai_generated", confidence: conf, needsConfirmation: false });
    // reuse template's attribute logic (factual-safe) for the structured attributes
    const base = template.generateListing(input, marketplace);
    return {
      provider: out.provider,
      note: "Generated by " + (out.provider === "gemini" ? "Gemini" : "Claude") + " from the seller's provided fields; missing facts are flagged, not invented.",
      fields: {
        title: f(json.title), shortTitle: f(json.shortTitle),
        bullets: f(json.bullets || []), description: f(json.description), keywords: f(json.keywords || []),
      },
      attributes: base.attributes,
    };
  } catch (e) {
    const fb = template.generateListing(input, marketplace);
    fb.note = "AI unavailable (" + e.message + ") — used built-in generator as fallback.";
    return fb;
  }
}
module.exports = { generateListing };
