// scripts/make-roadmap.js — builds "AutoList AI — Product Roadmap.pdf" (height-aware layout).
const PDFDocument = require("pdfkit");
const fs = require("fs"), path = require("path");
const OUT = path.join(__dirname, "..", "AutoList-AI-Roadmap.pdf");
const BLUE = "#2563eb", INK = "#0f172a", SOFT = "#586274", GREEN = "#16a34a", AMBER = "#b45309", RED = "#dc2626", LINE = "#e6e9ef";
const M = 54;
const doc = new PDFDocument({ size: "A4", margins: { top: M, bottom: M, left: M, right: M } });
doc.pipe(fs.createWriteStream(OUT));
const LEFT = M, RIGHT = doc.page.width - M, W = RIGHT - LEFT, BOTTOM = doc.page.height - M;
const ensure = (h) => { if (doc.y + h > BOTTOM) doc.addPage(); };
function h1(t) { ensure(46); doc.moveDown(0.5); doc.fillColor(BLUE).font("Helvetica-Bold").fontSize(16).text(t, LEFT, doc.y); const y = doc.y + 3; doc.moveTo(LEFT, y).lineTo(RIGHT, y).strokeColor(LINE).lineWidth(1).stroke(); doc.y = y + 8; }
function h2(t) { ensure(24); doc.moveDown(0.3); doc.fillColor(INK).font("Helvetica-Bold").fontSize(12).text(t, LEFT, doc.y); doc.moveDown(0.3); }
function p(t, o = {}) { ensure(18); doc.fillColor(o.color || SOFT).font(o.bold ? "Helvetica-Bold" : "Helvetica").fontSize(o.size || 10.5).text(t, LEFT, doc.y, { width: W, lineGap: 2.5 }); doc.moveDown(o.gap ?? 0.45); }
function bullet(t, color) { doc.font("Helvetica").fontSize(10.5); const tw = W - 16, hh = doc.heightOfString(t, { width: tw, lineGap: 2 }); ensure(hh + 4); const y = doc.y; doc.fillColor(color || BLUE).font("Helvetica-Bold").text("•", LEFT + 2, y, { width: 10 }); doc.fillColor(INK).font("Helvetica").text(t, LEFT + 16, y, { width: tw, lineGap: 2 }); doc.y = y + hh + 4; }
function step(n, title, body) { doc.font("Helvetica").fontSize(10); const tw = W - 34, bh = doc.heightOfString(body, { width: tw, lineGap: 2 }); doc.font("Helvetica-Bold").fontSize(11); const th = doc.heightOfString(title, { width: tw }); const rowH = th + bh + 9; ensure(rowH); const y = doc.y; doc.circle(LEFT + 9, y + 8, 9).fill(BLUE); doc.fillColor("#fff").font("Helvetica-Bold").fontSize(9.5).text(String(n), LEFT + 4, y + 4, { width: 10, align: "center" }); doc.fillColor(INK).font("Helvetica-Bold").fontSize(11).text(title, LEFT + 30, y, { width: tw }); doc.fillColor(SOFT).font("Helvetica").fontSize(10).text(body, LEFT + 30, y + th + 2, { width: tw, lineGap: 2 }); doc.y = y + rowH; }
function phase(tag, title, state, body, need) {
  const color = state === "done" ? GREEN : state === "next" ? BLUE : AMBER;
  doc.font("Helvetica").fontSize(10); const bh = doc.heightOfString(body, { width: W - 16, lineGap: 2 });
  ensure(bh + 46);
  const y = doc.y;
  doc.fillColor(color).font("Helvetica-Bold").fontSize(9).text(state === "done" ? "DONE" : state === "next" ? "NEXT" : "PLANNED", LEFT, y, { width: 60 });
  doc.fillColor(INK).font("Helvetica-Bold").fontSize(12).text(tag + " — " + title, LEFT + 66, y, { width: W - 66 });
  doc.fillColor(SOFT).font("Helvetica").fontSize(10).text(body, LEFT + 16, doc.y + 3, { width: W - 16, lineGap: 2 });
  if (need) { doc.fillColor(AMBER).font("Helvetica-Oblique").fontSize(9.5).text("Needs: " + need, LEFT + 16, doc.y + 2, { width: W - 16 }); }
  doc.moveDown(0.6);
}

// COVER
doc.rect(0, 0, doc.page.width, 140).fill(BLUE);
doc.fillColor("#fff").font("Helvetica-Bold").fontSize(28).text("AutoList AI", M, 40);
doc.font("Helvetica").fontSize(13).fillColor("#dbe6ff").text("Product Roadmap — from working MVP to a fabulous, at-scale seller platform", M, 82, { width: W });
doc.y = 158; doc.fillColor(SOFT).font("Helvetica").fontSize(9.5).text("Prepared by the AutoList AI CTO  ·  24 Sep 2026  ·  Live: https://autolistai.in", M, doc.y);
doc.moveDown(1);

h1("1. The goal");
p("AutoList AI should let any marketplace seller produce accurate, upload-ready listings at scale with almost no manual work — and it should feel like it already knows their business. Each seller gets their own AI that remembers what they sell, their brand voice, and their rules, and applies that to every listing. Text is written by Claude, images are processed/generated by an image AI, and the system is provider-pluggable so we can add more engines later. Built for large scale.", { color: INK });

h1("2. The seller journey we are building");
step(1, "Guided onboarding (ask first)", "On sign-up, AutoList asks a few questions: what you sell, categories, brand name(s), tone, target marketplaces, prohibited claims. Answers build the seller's Brand Profile.");
step(2, "Per-seller AI memory", "That Brand Profile + a sample listing the seller creates become the seller's persistent 'listing identity'. Every future generation uses it, so output matches how THEY sell — and it improves over time.");
step(3, "Create one sample listing", "The seller makes a single listing. The AI reads it, learns their patterns (attributes, phrasing, must-have fields) and saves them to memory.");
step(4, "Upload product images (ZIP)", "The seller uploads a ZIP of product photos. AutoList extracts them, hosts them, and turns them into public image links — matched to each product by filename/SKU.");
step(5, "Attach the marketplace sample file", "The seller attaches their exact Amazon/Flipkart sample file. AutoList fills every column natively — title, bullets, description, attributes, and the image links.");
step(6, "Watch it run, confirm each stage", "A live progress bar shows each step (uploading, converting links, generating, validating, filling). At key points it confirms with the seller (e.g. 'links converted correctly?').");
step(7, "Download & upload", "The seller downloads the finished file (and image ZIP) and uploads it to Seller Central. Later, with official APIs, this becomes one-click publishing.");

h1("3. Where we are today (strong foundation)");
bullet("Live product on your domain (https://autolistai.in) with HTTPS, auth, multi-tenant isolation.", GREEN);
bullet("AI listing generation (fact-safe) + validation + native Amazon/Flipkart template fill + CSV export.", GREEN);
bullet("One-click Bulk Pipeline (file → generate all → validate → export) with live progress, retry, cancel.", GREEN);
bullet("Background job engine, private file storage with signed URLs, usage limits + Razorpay billing (test mode).", GREEN);
bullet("Encrypted marketplace connections (safe mode) + a complete, secure Admin panel. 172 automated tests.", GREEN);
bullet("Provider abstraction already in place for text and images — ready to plug in Claude/OpenAI.", GREEN);

h1("4. What turns it 'fabulous' (the gap)");
bullet("Per-seller Brand Memory + guided onboarding (the app doesn't yet ask questions or store a brand identity).");
bullet("'Learn from a sample listing' — extract the seller's patterns into memory.");
bullet("Image ZIP → hosted links pipeline (extract, host on Cloudinary/S3, match to SKU, fill image columns).");
bullet("Live multi-provider AI actually connected: Claude (text), an image AI (photos/background), pluggable others.");
bullet("Step-by-step guided flow with confirmations at each stage (not just one button).");
bullet("Scale hardening when volume grows: Postgres, Redis/BullMQ workers, S3, CDN.");

h1("5. Architecture additions");
h2("Brand Memory (per business)");
p("A stored Brand Profile per seller: categories, brands, tone, prohibited claims, default attributes, and 'learned' patterns from their sample listing. Injected into every AI prompt so output is on-brand and consistent. This is the seller's private 'AI memory'.");
h2("Multi-provider AI");
p("Keep the provider registry: text → Claude (claude-sonnet-5), images → OpenAI/other, with a clean interface so we add engines without touching business logic. Each call logged with provider, model, tokens, cost. Facts are never invented, whichever engine is used.");
h2("Image pipeline");
p("Upload ZIP → extract → validate → host (Cloudinary or S3) → return CDN links → auto-match to SKU by filename → write into the marketplace template's image columns. Optional: white-background/marketplace-resize and AI background cleanup.");
h2("Scale path");
p("Today's zero-infra stack (node:sqlite, local storage, in-process queue) is perfect for launch and your own accounts. As sellers grow we swap: SQLite → Postgres, local files → S3+CDN, in-process worker → Redis/BullMQ. The code is written 'same shape' so these are clean swaps, not rewrites.");

h1("6. Roadmap (phased)");
phase("R1", "Brand Memory + Guided Onboarding", "next", "Onboarding questions on signup; store a Brand Profile per seller; a dashboard tailored to their answers; inject the profile into every generation. Learn from the seller's first sample listing.");
phase("R2", "Image ZIP → hosted links", "next", "Upload a product-image ZIP; extract + host on Cloudinary/S3; auto-match to SKUs; fill image columns; live progress + a 'links look right?' confirmation step.", "Cloudinary or S3 account (keys)");
phase("R3", "Live AI connected", "next", "Turn on Claude for text (done: add key) and an image AI for photos/background; per-provider settings; cost logging surfaced in Admin.", "ANTHROPIC_API_KEY (added), OPENAI/image key");
phase("R4", "Guided step-by-step flow", "planned", "Replace one-button bulk with a guided wizard that confirms at each stage (upload → map → links → generate → review → fill → download), using Brand Memory throughout.");
phase("R5", "Testing mode on your seller accounts", "planned", "Connect your real Amazon/Flipkart sample files end-to-end; run your own catalogues through it; refine on real data.");
phase("R6", "Scale + one-click publish", "planned", "Postgres + Redis + S3/CDN for volume; official Amazon SP-API / Flipkart Seller API publishing behind verified access (never passwords/OTP).", "Seller API approval; managed Postgres/Redis/S3");

h1("7. Services & keys to connect");
bullet("Anthropic (Claude) — text. Key added; set the value in Render to go live.", GREEN);
bullet("Image AI (OpenAI or similar) — product image generation/cleanup. Needs an API key.", AMBER);
bullet("Cloudinary or AWS S3 — host images from the ZIP and serve CDN links. Needs an account/keys.", AMBER);
bullet("Razorpay — live payments (keys + webhook https://autolistai.in/api/billing/webhook/razorpay). Optional now.", AMBER);
bullet("SMTP email — verification/reset emails. Optional.", AMBER);
bullet("Amazon SP-API / Flipkart Seller API — later, for direct publishing (your seller approval required).", AMBER);
p("Security: all keys are set in Render's dashboard, never in code or chat. Seller marketplace credentials are always encrypted; we never use passwords/OTP to automate a marketplace login.", { color: RED, bold: true });

h1("8. Costs (rough, pay-as-you-grow)");
bullet("Hosting (Render): ~$7/mo now; scales with instances/disk.");
bullet("Claude text: pay-per-use per listing (small); logged per request.");
bullet("Image AI: pay-per-image only if generating/cleaning images.");
bullet("Cloudinary/S3: low storage/bandwidth cost; free tiers exist to start.");
bullet("Razorpay: standard transaction fee, only on real payments.");

h1("9. Principles we will not break");
bullet("Never invent product facts — missing facts are flagged, not guessed.");
bullet("Never automate a marketplace with a seller's password/OTP (account-ban risk); use official APIs only.");
bullet("Never expose secrets or one seller's data to another; strict per-business isolation.");
bullet("Never show a success (or a download) unless it truly succeeded.");

h1("10. Immediate next steps");
step(1, "Approve this roadmap", "Confirm the journey (sections 2 & 6) matches your vision, or tell me what to change.");
step(2, "Add live AI key", "Set ANTHROPIC_API_KEY in Render (text goes live instantly, with safe fallback).");
step(3, "Send me the assets", "Your Amazon + Flipkart sample files, and a small product-image ZIP (5–10 photos) so I build R1–R2 against real data.");
step(4, "I build R1 then R2", "Brand Memory + onboarding first, then the image ZIP → links pipeline — in testing mode on your account, phase by phase.");
doc.moveDown(0.5);
doc.fillColor(SOFT).font("Helvetica").fontSize(9).text("AutoList AI — CTO roadmap. We build in phases, test on real data, and scale when volume demands it.", LEFT, doc.y, { width: W, align: "center" });

doc.end(); console.log("WROTE " + OUT);
